#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
picom &
feh --bg-scale /home/dragonify/Downloads/wallpapers/earth-in-space.png   


bspc monitor -d I II III IV V VI VII VIII 

bspc config border_width         3
bspc config window_gap           7
bspc config focused_border_color \#7e4d57
bspc config normal_border_color \#444

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^2'
bspc rule -a alacritty desktop='^1'
bspc rule -a lxterminal desktop='^1'
bspc rule -a xfce4-terminal desktop='^1'
